version: "3"

volumes:
  pg:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

services:
  noder:
    container_name: yooh
    image: node:latest
    volumes:
      - ./:/tmp
    entrypoint: /tmp/runServers.sh
    depends_on:
      - postgres
    ports:
      - "5173:5173"
      - "3000:3000"
    networks:
      - tcnetwork

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"
    networks:
      - tcnetwork

networks:
  tcnetwork:
    driver: bridge
