version: "3"

services:
  noder:
    container_name: yooh
    image: node
    volumes:
      - ./:/tmp
    entrypoint: /tmp/runServers.sh
    depends_on:
      - postgres
    ports:
      - "5173:5173"
      - "3000:3000"
    networks:
      - tcnetwork

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: transcendence
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tcnetwork

networks:
  tcnetwork:
    driver: bridge

volumes:
  data:
