version: "3"

services:
  noder:
    container_name: yooh
    image: node
    volumes:
      - ./:/tmp
    entrypoint: tail -f
    ports:
      - "5173:5173"
      - "3000:3000"
  data:
    container_name: jpark2
    image: postgres
    volumes:
      - ./data:/data
    expose:
      - 1234
