version: "3"

services:
  noder:
    container_name: yooh
    image: node
    volumes:
      - ./:/tmp
    entrypoint: tail -f
    ports:
      - "5173:5173"
      - "3000:3000"
    networks:
      - tcnetwork

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: transcendence
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - tcnetwork

networks:
  tcnetwork:
    driver: bridge
